using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Core.Models
{
    public class Peripheral
    {
        [XmlAttribute(AttributeName = "derivedFrom")]
        public string BasePeripheralName;

        [XmlElement(ElementName = "name")]
        public string Name;

        [XmlElement(ElementName = "description")]
        public string Description;

        [XmlElement(ElementName = "groupName")]
        public string GroupName { get; set; }

        [XmlElement(ElementName = "baseAddress")]
        public string BaseAddressString
        {
            get => string.Concat("0x", BaseAddress.ToString("X8"));
            set => BaseAddress = Convert.ToUInt32(value, 16);
        }

        [XmlIgnore]
        public uint BaseAddress { get; set; }

        [XmlArray("registers"), XmlArrayItem("register")]
        public List<Register> Registers;

        public override string ToString() => string.IsNullOrWhiteSpace(Description) ? $"{Name}" : $"{Name}: {Description}";
        
        public void AddDummyRegisters()
        {
            if (Registers.Any())
            {
                var dummies = GetDummyRegisters();
                Registers.AddRange(dummies);
                Registers = Registers.OrderBy(r => r.Offset.Bytes).ToList();

                Register firstRegister = Registers.FirstOrDefault();
                if (!(firstRegister is null) && firstRegister.Offset.Bytes != 0)
                {
                    Registers.Insert(0, Register.GetDummy(Width.FromBytes(firstRegister.Offset.Bytes), Offset.FromBytes(0)));
                }

                RenameDummyRegisters();
            }
        }

        public async Task GenerateCppHeaderAsync(CancellationToken ct)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// This file is autogenerated")
                .AppendLine()
                .AppendLine($"// {Name}")
                .AppendLine($"// {Description}")
                .AppendLine()
                .AppendLine("#pragma once")
                .AppendLine()
                .AppendLine("#include <cstdint>")
                .AppendLine("#include \"Register.h\"")
                .AppendLine()

                .AppendLine("namespace Core {")
                .Append(GenerateRegisterMasks())
                .Append(GenerateRegisters())
                .Append(CreatePeripherals())
                .AppendLine("}");

            await using var peripheralFile = File.Create($"{Name}.h");
            await using var peripheralHeader = new StreamWriter(peripheralFile, Encoding.UTF8);
            await peripheralHeader.WriteAsync(sb, ct);
        }

        private List<Register> GetDummyRegisters()
        {
            var registersGroupsSortedByOffset = Registers.GroupBy(r => r.Offset).OrderByDescending(g => g.Key.Bytes);
            var registerGroupsPairs =
                registersGroupsSortedByOffset.Zip(registersGroupsSortedByOffset.Skip(1), (g1, g2) => new { g1, g2 });

            var dummies = new List<Register>();
            foreach (var pair in registerGroupsPairs)
            {
                var nextRegisterOffset = Offset.FromBytes(pair.g2.Key.Bytes + pair.g2.First().Width.Bytes);
                if (nextRegisterOffset == pair.g1.Key)
                    continue;
                var nextRegisterWidth = Width.FromBytes(pair.g1.Key.Bytes - nextRegisterOffset.Bytes);
                dummies.Add(Register.GetDummy(nextRegisterWidth, nextRegisterOffset));
            }

            return dummies;
        }

        private void RenameDummyRegisters()
        {
            var dummies = Registers.Where(r => string.IsNullOrWhiteSpace(r.Name));
            foreach (var dummy in dummies)
            {
                var name = $"Reserved_{dummy.Offset.Bytes / 4}";
                dummy.Name = name;
                dummy.Description = name;
            }
        }

        private string GenerateRegisterMasks()
        {
            var sb = new StringBuilder();
            sb.AppendLine("    namespace RegisterMasks {")
                .AppendLine($"        namespace {Name} {{");

            foreach (Register register in Registers)
            {
                sb.Append(register.GenerateRegisterMask());
            }

            sb.AppendLine("        }")
                .AppendLine("    }")
                .AppendLine();
            return sb.ToString();
        }

        private string GenerateRegisters()
        {
            var sb = new StringBuilder();
            sb.AppendLine($"    namespace Registers {{")
                .AppendLine($"        namespace {Name} {{");

            foreach (Register register in Registers)
            {
                sb.AppendLine(register.GenerateClassCode(Name));
            }

            sb.AppendLine("        }")
                .AppendLine("    }")
                .AppendLine();
            return sb.ToString();
        }

        private string CreatePeripherals()
        {
            var sb = new StringBuilder();
            sb.AppendLine($"    namespace Peripherals {{")
                .AppendLine($"        class {Name} {{")
                .AppendLine("        public:")
                .AppendLine($"            {Name}() = delete;");

            foreach (Register register in Registers)
            {
                sb.AppendLine(register.GenerateFieldsCode(Name));
            }

            sb.AppendLine("        };")
                .AppendLine("    }")
                .AppendLine()
                .AppendLine(
                    $"    Peripherals::{Name} * const {Name.ToLower()} = reinterpret_cast<Peripherals::{Name} *>({BaseAddressString});");
            return sb.ToString();
        }
    }
}
